# Generated by Django 4.0.4 on 2022-04-29 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='rating_average',
        ),
    ]
